language: node_js
node_js:
  - 0.8

services: mongodb  
before_install:
 - sudo apt-get update -qq
 - yes | sudo apt-get install mongodb -y -qq
 - sudo apt-get install -qq coffeescript
 - sudo add-apt-repository ppa:travis-ci/zero-mq -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libzmq3
 - sudo service mongodb start

